# dbt_project.yml
name: dbt_warehouse
version: '1.0.0'
profile: dbt_warehouse
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

flags:
  use_colors: true
  send_anonymous_usage_stats: false
  bigquery_use_batch_source_freshness: true  # Faster freshness checks via TABLE_STORAGE

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
log-path: "logs"
packages-install-path: "dbt_packages"

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  dbt_warehouse:
    +materialized: view
    +persist_docs:
      relation: true
      columns: true

    staging:
      +schema: staging
      +tags: ['staging']

      yuman:
        +tags: ['staging', 'yuman']

      yuman_gcs:
        +tags: ['staging', 'yuman_gcs']

      nesp_co:
        +tags: ['staging', 'nesp_co']

      nesp_tech:
        +tags: ['staging', 'nesp_tech']

      oracle_neshu:
        +tags: ['staging', 'oracle_neshu']

      oracle_lcdp:
        +tags: ['staging', 'oracle_lcdp']

      oracle_neshu_gcs:
        +tags: ['staging', 'oracle_neshu_gcs']

      mssql_sage:
        +tags: ['staging', 'mssql_sage']

      gac:
        +tags: ['staging', 'gac']

    intermediate:
      +schema: intermediate
      +tags: ['intermediate']

      yuman:
        +tags: ['intermediate', 'yuman']

      oracle_neshu:
        +tags: ['intermediate', 'oracle_neshu']

      oracle_lcdp:
        +tags: ['intermediate', 'oracle_lcdp']

      mssql_sage:
        +tags: ['intermediate', 'mssql_sage']

      nesp_tech:
        +tags: ['intermediate', 'nesp_tech']

    marts:
      +schema: marts
      +tags: ['marts']

      yuman:
        +tags: ['marts', 'yuman']

      yuman_gcs:
        +tags: ['marts', 'yuman_gcs']

      oracle_neshu:
        +tags: ['marts', 'oracle_neshu']

      oracle_lcdp:
        +tags: ['marts', 'oracle_lcdp']

      oracle_neshu_gcs:
        +tags: ['marts', 'oracle_neshu_gcs']

      mssql_sage:
        +tags: ['marts', 'mssql_sage']

      nesp_tech:  
        +tags: ['marts', 'nesp_tech']

      gac:
        +tags: ['marts', 'gac']


# ✨ AJOUT de la section pour les seeds
seeds:
  dbt_warehouse:
    +materialized: seed
    +schema: reference
    +tags: ['reference']
    
    reference_data:
      # Yuman seeds
      yuman:
        ref_yuman__cp_metropole:
          +column_types:
            Code_Postal: STRING
            Metropole: STRING
        
        ref_yuman__cp_tech:
          +column_types:
            cp_depart_int: INTEGER
            cp_depart_texte: STRING
            cp_final_int: INTEGER
            cp_final_texte: STRING
            libelle_cp: STRING
            num_departement_texte: STRING
            nom_departement: STRING
            region_tech: STRING
        
        ref_yuman__dpt_metropole:
          +column_types:
            Departement: STRING
            Metropole: STRING
        
        ref_yuman__machine_clean:
          +column_types:
            Machine_Brut: STRING
            MACHINE: STRING
        
        ref_yuman__marque_clean:
          +column_types:
            NOM_DU_TECHNICIEN: STRING
            MARQUE: STRING
        
        ref_yuman__technicien_clean:
          +column_types:
            TECHNICIEN: STRING
            Nom: STRING
            Prenom: STRING
            Nom_Prenom: STRING
            EQUIPE: STRING
        
        ref_yuman__type_inter_clean:
          +column_types:
            Type_intervention_Brut: STRING
            TYPE_INTER: STRING
        
        ref_yuman__tarification_clean:
          +column_types:
            TYPE_INTER: STRING
            MACHINE: STRING
            KEY: STRING
            MARQUE: STRING
            METROPOLE: STRING
            Type_tarif: STRING
            Montant: INTEGER
            PROD: INTEGER
        
        ref_yuman__tech_agence:
          +column_types:
            nom: STRING
            prenom: STRING
            agence: STRING
            equipe: STRING
        
        ref_yuman__tech_nomad:
          +column_types:
            user_id: INTEGER
            user_name: STRING
            nomad_id: STRING
            user_stock_name: STRING
      
      # Oracle Neshu seeds
      oracle_neshu:
        ref_oracle_neshu__valo_parc_machine:
          +column_types:
            machine_modele: STRING
            montant_inv: FLOAT 
        
        ref_oracle_neshu__roadman_gea:
          +column_types:
            roadman_code: STRING
            gea_code: STRING
      
      # MSSQL Sage seeds
      mssql_sage:
        ref_mssql_sage__code_analytique_bu:
          +column_types:
            code_analytique: STRING
            code_analytique_bu: STRING
        
        ref_mssql_sage__code_comptable_bu:
          +column_types:
            code_comptable: STRING
            designation_compte: STRING
            macro_categorie_pnl_bu: STRING

# Configuration des snapshots
snapshots:
  dbt_warehouse:
    +target_schema: "{{ 'snapshots_dev' if target.name == 'dev' else 'snapshots' }}"
    +tags: ['snapshots']
    
    oracle_neshu:
      +tags: ['snapshots', 'oracle_neshu']