# dbt_project.yml
name: dbt_warehouse
version: '1.0.0'
profile: dbt_warehouse
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

flags:
  use_colors: true
  send_anonymous_usage_stats: false

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
log-path: "logs"
packages-install-path: "dbt_packages"

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  dbt_warehouse:
    +materialized: view
    +persist_docs:
      relation: true
      columns: true
    staging:
      +schema: staging
      +tags: ['staging']
    intermediate:
      +schema: intermediate
      +tags: ['intermediate']
    marts:
      +schema: marts
      +tags: ['marts']

# ✨ AJOUT de la section pour les seeds
seeds:
  dbt_warehouse:
    +materialized: seed
    +schema: reference
    +tags: ['reference']
    
    reference_data:
      cp_metropole:
        +column_types:
          Code_Postal: STRING
          Metropole: STRING
      
      dpt_metropole:
        +column_types:
          Departement: STRING
          Metropole: STRING
      
      machines_clean:
        +column_types:
          Machine_Brut: STRING
          MACHINE: STRING
      
      marque_clean:
        +column_types:
          NOM_DU_TECHNICIEN: STRING
          MARQUE: STRING
      
      techniciens_clean:
        +column_types:
          TECHNICIEN: STRING
          Nom: STRING
          Prenom: STRING
          Nom_Prenom: STRING
          EQUIPE: STRING
      
      type_inter_clean:
        +column_types:
          Type_intervention_Brut: STRING
          TYPE_INTER: STRING
      
      tarification_ref_clean:
        +column_types:
          TYPE_INTER: STRING
          MACHINE: STRING
          KEY: STRING
          MARQUE: STRING
          METROPOLE: STRING
          Type_tarif: STRING
          Montant: INTEGER
          PROD: INTEGER