# File: transform/profiles.yml
dbt_warehouse:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('DBT_BIGQUERY_PROJECT') }}"
      dataset: "{{ env_var('DBT_BIGQUERY_DATASET_DEV') }}"
      threads: 8
      location: europe-west1
      keyfile: "{{ env_var('DBT_BIGQUERY_KEYFILE') }}"

    dev_analyst:
      type: bigquery
      method: service-account
      project: "{{ env_var('DBT_BIGQUERY_PROJECT') }}"
      dataset: "{{ env_var('DBT_BIGQUERY_DATASET_DEV') }}"  # Utilisera dev_analyst via .env
      threads: 8
      location: europe-west1
      keyfile: "{{ env_var('DBT_BIGQUERY_KEYFILE') }}"
      
    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('DBT_BIGQUERY_PROJECT') }}"
      dataset: "{{ env_var('DBT_BIGQUERY_DATASET_PROD') }}"
      threads: 16
      location: europe-west1
      keyfile: "{{ env_var('DBT_BIGQUERY_KEYFILE') }}"