

-- Fait mince : délai de traitement et tarification des interventions Yuman.
-- Toute la logique métier (normalisation, tarification, calcul du délai en jours
-- ouvrés) vit désormais dans int_yuman__interventions. Ce modèle ne fait qu'exposer
-- le contrat de colonnes historique attendu par le rapport Power BI
-- (exposure neshu / workorder_delai). Aucune dépendance fait→fait.

select
    demand_id,
    workorder_id,
    material_id,
    site_id,
    client_id,
    technician_id,
    manager_id,
    demand_description,
    demand_status,
    demand_created_at,
    demand_updated_at,
    demand_category_name,
    workorder_number,
    workorder_category,
    workorder_status,
    workorder_technician_name,
    workorder_date_creation,
    workorder_report,
    workorder_motif_non_intervention,
    workorder_detail_non_intervention,
    workorder_raison_mise_en_pause,
    workorder_explication_mise_en_pause,
    date_planned,
    date_started,
    date_done,
    partner_name,
    client_code,
    client_name,
    client_category,
    client_is_active,
    site_code,
    site_name,
    site_address,
    site_postal_code,
    material_serial_number,
    workorder_type_raw,
    machine_raw,
    workorder_type_clean,
    machine_clean,
    metropolitan,
    metropole_city,
    technician_equipe,
    recurrence_count,
    pricing_type,
    pricing_key_used,
    to_invoice,
    amount,
    prod_number,
    billing_validation_status,
    date_creation_ref,
    delai_jours_ouvres,
    type_delai,
    famille_neshu
from `evs-datastack-prod`.`prod_intermediate`.`int_yuman__interventions`